blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/holiday-calendar/holiday-calendar-java/discussions
    about: Use GitHub Discussions for questions and general discussion
